<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stylesheet>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<!-- This file generated by generate_MARC21Languages.pl -->
 <xsl:template name="languageCodeText">
 <xsl:param name="code"/>
 <xsl:choose>
 <xsl:when test="$code='abk'"><xsl:text>Abchasisch</xsl:text></xsl:when>
 <xsl:when test="$code='ace'"><xsl:text>Achinesisch</xsl:text></xsl:when>
 <xsl:when test="$code='ach'"><xsl:text>Acholi-Sprache</xsl:text></xsl:when>
 <xsl:when test="$code='ada'"><xsl:text>Adangme</xsl:text></xsl:when>
 <xsl:when test="$code='ady'"><xsl:text>Adygisch</xsl:text></xsl:when>
 <xsl:when test="$code='aar'"><xsl:text>Afar</xsl:text></xsl:when>
 <xsl:when test="$code='afh'"><xsl:text>Afrihili (Künstliche Sprache)</xsl:text></xsl:when>
 <xsl:when test="$code='afr'"><xsl:text>Afrikaans</xsl:text></xsl:when>
 <xsl:when test="$code='afa'"><xsl:text>Afroasiatische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='ain'"><xsl:text>Ainu</xsl:text></xsl:when>
 <xsl:when test="$code='aka'"><xsl:text>Akan</xsl:text></xsl:when>
 <xsl:when test="$code='akk'"><xsl:text>Akkadisch</xsl:text></xsl:when>
 <xsl:when test="$code='alb'"><xsl:text>Albanisch</xsl:text></xsl:when>
 <xsl:when test="$code='ale'"><xsl:text>Aleutisch</xsl:text></xsl:when>
 <xsl:when test="$code='alg'"><xsl:text>Algonkin-Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='alt'"><xsl:text>Altaisch</xsl:text></xsl:when>
 <xsl:when test="$code='tut'"><xsl:text>Altaische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='amh'"><xsl:text>Amharisch</xsl:text></xsl:when>
 <xsl:when test="$code='anp'"><xsl:text>Angika</xsl:text></xsl:when>
 <xsl:when test="$code='apa'"><xsl:text>Apachen-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='ara'"><xsl:text>Arabisch</xsl:text></xsl:when>
 <xsl:when test="$code='arg'"><xsl:text>Aragonesisch</xsl:text></xsl:when>
 <xsl:when test="$code='arc'"><xsl:text>Aramäisch</xsl:text></xsl:when>
 <xsl:when test="$code='arp'"><xsl:text>Arapaho</xsl:text></xsl:when>
 <xsl:when test="$code='arw'"><xsl:text>Arawakisch</xsl:text></xsl:when>
 <xsl:when test="$code='arm'"><xsl:text>Armenisch</xsl:text></xsl:when>
 <xsl:when test="$code='rup'"><xsl:text>Aromunisch</xsl:text></xsl:when>
 <xsl:when test="$code='art'"><xsl:text>Kunstsprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='asm'"><xsl:text>Assamesisch</xsl:text></xsl:when>
 <xsl:when test="$code='ath'"><xsl:text>Athapaskische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='aus'"><xsl:text>Australische Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='map'"><xsl:text>Austronesische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='ava'"><xsl:text>Awarisch</xsl:text></xsl:when>
 <xsl:when test="$code='ave'"><xsl:text>Avestisch</xsl:text></xsl:when>
 <xsl:when test="$code='awa'"><xsl:text>Awadhi</xsl:text></xsl:when>
 <xsl:when test="$code='aym'"><xsl:text>Aymara</xsl:text></xsl:when>
 <xsl:when test="$code='aze'"><xsl:text>Aserbeidschanisch</xsl:text></xsl:when>
 <xsl:when test="$code='ast'"><xsl:text>Asturisch</xsl:text></xsl:when>
 <xsl:when test="$code='ban'"><xsl:text>Balinesisch</xsl:text></xsl:when>
 <xsl:when test="$code='bat'"><xsl:text>Baltische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='bal'"><xsl:text>Belutschisch</xsl:text></xsl:when>
 <xsl:when test="$code='bam'"><xsl:text>Bambara</xsl:text></xsl:when>
 <xsl:when test="$code='bai'"><xsl:text>Bamileke-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='bad'"><xsl:text>Banda-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='bnt'"><xsl:text>Bantu (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='bas'"><xsl:text>Basa</xsl:text></xsl:when>
 <xsl:when test="$code='bak'"><xsl:text>Baschkirisch</xsl:text></xsl:when>
 <xsl:when test="$code='baq'"><xsl:text>Baskisch</xsl:text></xsl:when>
 <xsl:when test="$code='btk'"><xsl:text>Batak</xsl:text></xsl:when>
 <xsl:when test="$code='bej'"><xsl:text>Beja</xsl:text></xsl:when>
 <xsl:when test="$code='bel'"><xsl:text>Weißrussisch</xsl:text></xsl:when>
 <xsl:when test="$code='bem'"><xsl:text>Bemba</xsl:text></xsl:when>
 <xsl:when test="$code='ben'"><xsl:text>Bengalisch</xsl:text></xsl:when>
 <xsl:when test="$code='ber'"><xsl:text>Berbersprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='bho'"><xsl:text>Bhojpuri</xsl:text></xsl:when>
 <xsl:when test="$code='bih'"><xsl:text>Bihari-Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='bik'"><xsl:text>Bikol</xsl:text></xsl:when>
 <xsl:when test="$code='byn'"><xsl:text>Bilin</xsl:text></xsl:when>
 <xsl:when test="$code='bis'"><xsl:text>Bislama</xsl:text></xsl:when>
 <xsl:when test="$code='zbl'"><xsl:text>Bliss-Symbole</xsl:text></xsl:when>
 <xsl:when test="$code='bos'"><xsl:text>Bosnisch</xsl:text></xsl:when>
 <xsl:when test="$code='bra'"><xsl:text>Braj</xsl:text></xsl:when>
 <xsl:when test="$code='bre'"><xsl:text>Bretonisch</xsl:text></xsl:when>
 <xsl:when test="$code='bug'"><xsl:text>Bugis</xsl:text></xsl:when>
 <xsl:when test="$code='bul'"><xsl:text>Bulgarisch</xsl:text></xsl:when>
 <xsl:when test="$code='bua'"><xsl:text>Buriat</xsl:text></xsl:when>
 <xsl:when test="$code='bur'"><xsl:text>Burmesisch</xsl:text></xsl:when>
 <xsl:when test="$code='cad'"><xsl:text>Caddo</xsl:text></xsl:when>
 <xsl:when test="$code='car'"><xsl:text>Carib</xsl:text></xsl:when>
 <xsl:when test="$code='cat'"><xsl:text>Katalanisch</xsl:text></xsl:when>
 <xsl:when test="$code='cau'"><xsl:text>Kaukasische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='ceb'"><xsl:text>Cebuano</xsl:text></xsl:when>
 <xsl:when test="$code='cel'"><xsl:text>Keltische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='cai'"><xsl:text>Indianersprachen, Zentralamerika (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='chg'"><xsl:text>Tschagataisch</xsl:text></xsl:when>
 <xsl:when test="$code='cmc'"><xsl:text>Cham-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='cha'"><xsl:text>Chamorro</xsl:text></xsl:when>
 <xsl:when test="$code='che'"><xsl:text>Tschetschenisch</xsl:text></xsl:when>
 <xsl:when test="$code='chr'"><xsl:text>Cherokee</xsl:text></xsl:when>
 <xsl:when test="$code='chy'"><xsl:text>Cheyenne</xsl:text></xsl:when>
 <xsl:when test="$code='chb'"><xsl:text>Chibcha</xsl:text></xsl:when>
 <xsl:when test="$code='chi'"><xsl:text>Chinesisch</xsl:text></xsl:when>
 <xsl:when test="$code='chn'"><xsl:text>Chinook-Jargon</xsl:text></xsl:when>
 <xsl:when test="$code='chp'"><xsl:text>Chipewyan</xsl:text></xsl:when>
 <xsl:when test="$code='cho'"><xsl:text>Choctaw</xsl:text></xsl:when>
 <xsl:when test="$code='chu'"><xsl:text>Kirchenslawisch</xsl:text></xsl:when>
 <xsl:when test="$code='chk'"><xsl:text>Chuukesisch</xsl:text></xsl:when>
 <xsl:when test="$code='chv'"><xsl:text>Tschuwaschisch</xsl:text></xsl:when>
 <xsl:when test="$code='cop'"><xsl:text>Koptisch</xsl:text></xsl:when>
 <xsl:when test="$code='cor'"><xsl:text>Kornisch</xsl:text></xsl:when>
 <xsl:when test="$code='cos'"><xsl:text>Korsisch</xsl:text></xsl:when>
 <xsl:when test="$code='cre'"><xsl:text>Cree</xsl:text></xsl:when>
 <xsl:when test="$code='mus'"><xsl:text>Creek</xsl:text></xsl:when>
 <xsl:when test="$code='crp'"><xsl:text>Kreolische und Pidgin-Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='cpe'"><xsl:text>Kreolische und Pidgin-Sprachen, englisch-basierend (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='cpf'"><xsl:text>Kreolische und Pidgin-Sprachen, französisch-basierend (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='cpp'"><xsl:text>Kreolische und Pidgin-Sprachen, portugiesisch-basierend (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='crh'"><xsl:text>Krimtatarisch</xsl:text></xsl:when>
 <xsl:when test="$code='hrv'"><xsl:text>Kroatisch</xsl:text></xsl:when>
 <xsl:when test="$code='cus'"><xsl:text>Kuschitische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='cze'"><xsl:text>Tschechisch</xsl:text></xsl:when>
 <xsl:when test="$code='dak'"><xsl:text>Dakota</xsl:text></xsl:when>
 <xsl:when test="$code='dan'"><xsl:text>Dänisch</xsl:text></xsl:when>
 <xsl:when test="$code='dar'"><xsl:text>Darginisch</xsl:text></xsl:when>
 <xsl:when test="$code='day'"><xsl:text>Dajakisch</xsl:text></xsl:when>
 <xsl:when test="$code='del'"><xsl:text>Delaware</xsl:text></xsl:when>
 <xsl:when test="$code='din'"><xsl:text>Dinka</xsl:text></xsl:when>
 <xsl:when test="$code='div'"><xsl:text>Dhivehi</xsl:text></xsl:when>
 <xsl:when test="$code='doi'"><xsl:text>Dogri</xsl:text></xsl:when>
 <xsl:when test="$code='dgr'"><xsl:text>Dogrib</xsl:text></xsl:when>
 <xsl:when test="$code='dra'"><xsl:text>Drawidische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='dua'"><xsl:text>Duala</xsl:text></xsl:when>
 <xsl:when test="$code='dut'"><xsl:text>Niederländisch</xsl:text></xsl:when>
 <xsl:when test="$code='dum'"><xsl:text>Mittelniederländisch (ca. 1050-1350)</xsl:text></xsl:when>
 <xsl:when test="$code='dyu'"><xsl:text>Dyula</xsl:text></xsl:when>
 <xsl:when test="$code='dzo'"><xsl:text>Dzongkha</xsl:text></xsl:when>
 <xsl:when test="$code='frs'"><xsl:text>Ostfriesisch</xsl:text></xsl:when>
 <xsl:when test="$code='bin'"><xsl:text>Edo</xsl:text></xsl:when>
 <xsl:when test="$code='efi'"><xsl:text>Efik</xsl:text></xsl:when>
 <xsl:when test="$code='egy'"><xsl:text>Ägyptisch</xsl:text></xsl:when>
 <xsl:when test="$code='eka'"><xsl:text>Ekajuk</xsl:text></xsl:when>
 <xsl:when test="$code='elx'"><xsl:text>Elamisch</xsl:text></xsl:when>
 <xsl:when test="$code='eng'"><xsl:text>Englisch</xsl:text></xsl:when>
 <xsl:when test="$code='enm'"><xsl:text>Mittelenglisch (1100-1500)</xsl:text></xsl:when>
 <xsl:when test="$code='ang'"><xsl:text>Altenglisch (ca. 450-1100)</xsl:text></xsl:when>
 <xsl:when test="$code='myv'"><xsl:text>Ersjanisch</xsl:text></xsl:when>
 <xsl:when test="$code='epo'"><xsl:text>Esperanto</xsl:text></xsl:when>
 <xsl:when test="$code='est'"><xsl:text>Estnisch</xsl:text></xsl:when>
 <xsl:when test="$code='gez'"><xsl:text>Äthiopisch</xsl:text></xsl:when>
 <xsl:when test="$code='ewe'"><xsl:text>Ewe</xsl:text></xsl:when>
 <xsl:when test="$code='ewo'"><xsl:text>Ewondo</xsl:text></xsl:when>
 <xsl:when test="$code='fan'"><xsl:text>Fang</xsl:text></xsl:when>
 <xsl:when test="$code='fat'"><xsl:text>Fante</xsl:text></xsl:when>
 <xsl:when test="$code='fao'"><xsl:text>Faröisch</xsl:text></xsl:when>
 <xsl:when test="$code='fij'"><xsl:text>Fidschianisch</xsl:text></xsl:when>
 <xsl:when test="$code='fil'"><xsl:text>Filipinisch</xsl:text></xsl:when>
 <xsl:when test="$code='fin'"><xsl:text>Finnisch</xsl:text></xsl:when>
 <xsl:when test="$code='fiu'"><xsl:text>Finno-ugrische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='fon'"><xsl:text>Fon</xsl:text></xsl:when>
 <xsl:when test="$code='fre'"><xsl:text>Französisch</xsl:text></xsl:when>
 <xsl:when test="$code='frm'"><xsl:text>Mittelfranzösisch (ca. 1300-1600)</xsl:text></xsl:when>
 <xsl:when test="$code='fro'"><xsl:text>Altfranzösisch (ca. 842-1300)</xsl:text></xsl:when>
 <xsl:when test="$code='fry'"><xsl:text>Friesisch</xsl:text></xsl:when>
 <xsl:when test="$code='fur'"><xsl:text>Furlanisch</xsl:text></xsl:when>
 <xsl:when test="$code='ful'"><xsl:text>Fula</xsl:text></xsl:when>
 <xsl:when test="$code='gaa'"><xsl:text>Gã</xsl:text></xsl:when>
 <xsl:when test="$code='glg'"><xsl:text>Galizisch</xsl:text></xsl:when>
 <xsl:when test="$code='lug'"><xsl:text>Ganda</xsl:text></xsl:when>
 <xsl:when test="$code='gay'"><xsl:text>Gayo</xsl:text></xsl:when>
 <xsl:when test="$code='gba'"><xsl:text>Gbaya</xsl:text></xsl:when>
 <xsl:when test="$code='geo'"><xsl:text>Georgisch</xsl:text></xsl:when>
 <xsl:when test="$code='ger'"><xsl:text>Deutsch</xsl:text></xsl:when>
 <xsl:when test="$code='gmh'"><xsl:text>Mittelhochdeutsch (ca. 1050-1500)</xsl:text></xsl:when>
 <xsl:when test="$code='goh'"><xsl:text>Althochdeutsch (ca. 750-1050)</xsl:text></xsl:when>
 <xsl:when test="$code='gem'"><xsl:text>Germanische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='gil'"><xsl:text>Gilbertesisch</xsl:text></xsl:when>
 <xsl:when test="$code='gon'"><xsl:text>Gondi</xsl:text></xsl:when>
 <xsl:when test="$code='gor'"><xsl:text>Gorontalo</xsl:text></xsl:when>
 <xsl:when test="$code='got'"><xsl:text>Gotisch</xsl:text></xsl:when>
 <xsl:when test="$code='grb'"><xsl:text>Grebo</xsl:text></xsl:when>
 <xsl:when test="$code='grc'"><xsl:text>Altgriechisch (bis 1453)</xsl:text></xsl:when>
 <xsl:when test="$code='gre'"><xsl:text>Neugriechisch (1453-)</xsl:text></xsl:when>
 <xsl:when test="$code='grn'"><xsl:text>Guarani</xsl:text></xsl:when>
 <xsl:when test="$code='guj'"><xsl:text>Gujarati</xsl:text></xsl:when>
 <xsl:when test="$code='gwi'"><xsl:text>Gwich'in</xsl:text></xsl:when>
 <xsl:when test="$code='hai'"><xsl:text>Haida</xsl:text></xsl:when>
 <xsl:when test="$code='hat'"><xsl:text>Haitianisches französisches Kreol</xsl:text></xsl:when>
 <xsl:when test="$code='hau'"><xsl:text>Hausa</xsl:text></xsl:when>
 <xsl:when test="$code='haw'"><xsl:text>Hawaiianisch</xsl:text></xsl:when>
 <xsl:when test="$code='heb'"><xsl:text>Hebräisch</xsl:text></xsl:when>
 <xsl:when test="$code='her'"><xsl:text>Herero</xsl:text></xsl:when>
 <xsl:when test="$code='hil'"><xsl:text>Hiligaynon</xsl:text></xsl:when>
 <xsl:when test="$code='hin'"><xsl:text>Hindi</xsl:text></xsl:when>
 <xsl:when test="$code='hmo'"><xsl:text>Hiri Motu</xsl:text></xsl:when>
 <xsl:when test="$code='hit'"><xsl:text>Hethitisch</xsl:text></xsl:when>
 <xsl:when test="$code='hmn'"><xsl:text>Hmong</xsl:text></xsl:when>
 <xsl:when test="$code='hun'"><xsl:text>Ungarisch</xsl:text></xsl:when>
 <xsl:when test="$code='hup'"><xsl:text>Hupa</xsl:text></xsl:when>
 <xsl:when test="$code='iba'"><xsl:text>Iban</xsl:text></xsl:when>
 <xsl:when test="$code='ice'"><xsl:text>Isländisch</xsl:text></xsl:when>
 <xsl:when test="$code='ido'"><xsl:text>Ido</xsl:text></xsl:when>
 <xsl:when test="$code='ibo'"><xsl:text>Igbo</xsl:text></xsl:when>
 <xsl:when test="$code='ijo'"><xsl:text>Ijo</xsl:text></xsl:when>
 <xsl:when test="$code='ilo'"><xsl:text>Iloko</xsl:text></xsl:when>
 <xsl:when test="$code='smn'"><xsl:text>Inarisamisch</xsl:text></xsl:when>
 <xsl:when test="$code='inc'"><xsl:text>Indoarische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='ine'"><xsl:text>Indoeuropäische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='ind'"><xsl:text>Indonesisch</xsl:text></xsl:when>
 <xsl:when test="$code='inh'"><xsl:text>Inguschisch</xsl:text></xsl:when>
 <xsl:when test="$code='ina'"><xsl:text>Interlingua (Internationale Hilfssprachen-Vereinigung)</xsl:text></xsl:when>
 <xsl:when test="$code='ile'"><xsl:text>Interlingue</xsl:text></xsl:when>
 <xsl:when test="$code='iku'"><xsl:text>Inuktitut</xsl:text></xsl:when>
 <xsl:when test="$code='ipk'"><xsl:text>Inupiaq</xsl:text></xsl:when>
 <xsl:when test="$code='ira'"><xsl:text>Iranische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='gle'"><xsl:text>Irisch</xsl:text></xsl:when>
 <xsl:when test="$code='mga'"><xsl:text>Mittelirisch (ca. 1100-1550)</xsl:text></xsl:when>
 <xsl:when test="$code='sga'"><xsl:text>Altirisch (bis 1100)</xsl:text></xsl:when>
 <xsl:when test="$code='iro'"><xsl:text>Irokesische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='ita'"><xsl:text>Italienisch</xsl:text></xsl:when>
 <xsl:when test="$code='jpn'"><xsl:text>Japanisch</xsl:text></xsl:when>
 <xsl:when test="$code='jav'"><xsl:text>Javanisch</xsl:text></xsl:when>
 <xsl:when test="$code='jrb'"><xsl:text>Judäo-Arabisch</xsl:text></xsl:when>
 <xsl:when test="$code='jpr'"><xsl:text>Judäo-Persisch</xsl:text></xsl:when>
 <xsl:when test="$code='kbd'"><xsl:text>Kabardinisch</xsl:text></xsl:when>
 <xsl:when test="$code='kab'"><xsl:text>Kabylisch</xsl:text></xsl:when>
 <xsl:when test="$code='kac'"><xsl:text>Kachin</xsl:text></xsl:when>
 <xsl:when test="$code='kal'"><xsl:text>Kalâtdlisut</xsl:text></xsl:when>
 <xsl:when test="$code='kam'"><xsl:text>Kamba</xsl:text></xsl:when>
 <xsl:when test="$code='kan'"><xsl:text>Kannada</xsl:text></xsl:when>
 <xsl:when test="$code='kau'"><xsl:text>Kanuri</xsl:text></xsl:when>
 <xsl:when test="$code='krc'"><xsl:text>Karatschaiisch-Balkarisch</xsl:text></xsl:when>
 <xsl:when test="$code='kaa'"><xsl:text>Karakalpakisch</xsl:text></xsl:when>
 <xsl:when test="$code='krl'"><xsl:text>Karelisch</xsl:text></xsl:when>
 <xsl:when test="$code='kar'"><xsl:text>Karenische Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='kas'"><xsl:text>Kaschmirisch</xsl:text></xsl:when>
 <xsl:when test="$code='csb'"><xsl:text>Kaschubisch</xsl:text></xsl:when>
 <xsl:when test="$code='kaw'"><xsl:text>Kawi</xsl:text></xsl:when>
 <xsl:when test="$code='kaz'"><xsl:text>Kasachisch</xsl:text></xsl:when>
 <xsl:when test="$code='kha'"><xsl:text>Khasi</xsl:text></xsl:when>
 <xsl:when test="$code='khm'"><xsl:text>Kambodschanisch</xsl:text></xsl:when>
 <xsl:when test="$code='khi'"><xsl:text>Khoisan-Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='kho'"><xsl:text>Sakisch</xsl:text></xsl:when>
 <xsl:when test="$code='kik'"><xsl:text>Kikuyu</xsl:text></xsl:when>
 <xsl:when test="$code='kmb'"><xsl:text>Kimbundu</xsl:text></xsl:when>
 <xsl:when test="$code='kin'"><xsl:text>Kinyarwanda</xsl:text></xsl:when>
 <xsl:when test="$code='tlh'"><xsl:text>Klingonisch (Kunstsprache)</xsl:text></xsl:when>
 <xsl:when test="$code='kom'"><xsl:text>Komi</xsl:text></xsl:when>
 <xsl:when test="$code='kon'"><xsl:text>Kongo</xsl:text></xsl:when>
 <xsl:when test="$code='kok'"><xsl:text>Konkani</xsl:text></xsl:when>
 <xsl:when test="$code='kut'"><xsl:text>Kootenai</xsl:text></xsl:when>
 <xsl:when test="$code='kor'"><xsl:text>Koreanisch</xsl:text></xsl:when>
 <xsl:when test="$code='kos'"><xsl:text>Kosraeanisch</xsl:text></xsl:when>
 <xsl:when test="$code='kpe'"><xsl:text>Kpelle</xsl:text></xsl:when>
 <xsl:when test="$code='kro'"><xsl:text>Kru (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='kua'"><xsl:text>Kuanyama</xsl:text></xsl:when>
 <xsl:when test="$code='kum'"><xsl:text>Kumykisch</xsl:text></xsl:when>
 <xsl:when test="$code='kur'"><xsl:text>Kurdisch</xsl:text></xsl:when>
 <xsl:when test="$code='kru'"><xsl:text>Kurukh</xsl:text></xsl:when>
 <xsl:when test="$code='kir'"><xsl:text>Kirgisisch</xsl:text></xsl:when>
 <xsl:when test="$code='lad'"><xsl:text>Ladino</xsl:text></xsl:when>
 <xsl:when test="$code='lah'"><xsl:text>Lahndā</xsl:text></xsl:when>
 <xsl:when test="$code='lam'"><xsl:text>Lamba (Zambia und Kongo)</xsl:text></xsl:when>
 <xsl:when test="$code='lao'"><xsl:text>Laotisch</xsl:text></xsl:when>
 <xsl:when test="$code='lat'"><xsl:text>Latein</xsl:text></xsl:when>
 <xsl:when test="$code='lav'"><xsl:text>Lettisch</xsl:text></xsl:when>
 <xsl:when test="$code='lez'"><xsl:text>Lesgisch</xsl:text></xsl:when>
 <xsl:when test="$code='lim'"><xsl:text>Limburgisch</xsl:text></xsl:when>
 <xsl:when test="$code='lin'"><xsl:text>Lingala</xsl:text></xsl:when>
 <xsl:when test="$code='lit'"><xsl:text>Litauisch</xsl:text></xsl:when>
 <xsl:when test="$code='jbo'"><xsl:text>Lojban (Kunstsprache)</xsl:text></xsl:when>
 <xsl:when test="$code='nds'"><xsl:text>Niederdeutsch</xsl:text></xsl:when>
 <xsl:when test="$code='dsb'"><xsl:text>Niederserbisch</xsl:text></xsl:when>
 <xsl:when test="$code='loz'"><xsl:text>Lozi</xsl:text></xsl:when>
 <xsl:when test="$code='lub'"><xsl:text>Luba-Katanga</xsl:text></xsl:when>
 <xsl:when test="$code='lua'"><xsl:text>Luba-Lulua</xsl:text></xsl:when>
 <xsl:when test="$code='lui'"><xsl:text>Luiseño</xsl:text></xsl:when>
 <xsl:when test="$code='smj'"><xsl:text>Lulesamisch</xsl:text></xsl:when>
 <xsl:when test="$code='lun'"><xsl:text>Chilunda</xsl:text></xsl:when>
 <xsl:when test="$code='luo'"><xsl:text>Luo (Kenia und Tansania)</xsl:text></xsl:when>
 <xsl:when test="$code='lus'"><xsl:text>Lushai</xsl:text></xsl:when>
 <xsl:when test="$code='ltz'"><xsl:text>Luxemburgisch</xsl:text></xsl:when>
 <xsl:when test="$code='mac'"><xsl:text>Mazedonisch</xsl:text></xsl:when>
 <xsl:when test="$code='mad'"><xsl:text>Maduresisch</xsl:text></xsl:when>
 <xsl:when test="$code='mag'"><xsl:text>Magahi</xsl:text></xsl:when>
 <xsl:when test="$code='mai'"><xsl:text>Maithili</xsl:text></xsl:when>
 <xsl:when test="$code='mak'"><xsl:text>Makassar</xsl:text></xsl:when>
 <xsl:when test="$code='mlg'"><xsl:text>Malagassisch</xsl:text></xsl:when>
 <xsl:when test="$code='may'"><xsl:text>Malaiisch</xsl:text></xsl:when>
 <xsl:when test="$code='mal'"><xsl:text>Malayalam</xsl:text></xsl:when>
 <xsl:when test="$code='mlt'"><xsl:text>Maltesisch</xsl:text></xsl:when>
 <xsl:when test="$code='mnc'"><xsl:text>Mandschurisch</xsl:text></xsl:when>
 <xsl:when test="$code='mdr'"><xsl:text>Mandar</xsl:text></xsl:when>
 <xsl:when test="$code='man'"><xsl:text>Mandingo</xsl:text></xsl:when>
 <xsl:when test="$code='mni'"><xsl:text>Manipuri</xsl:text></xsl:when>
 <xsl:when test="$code='mno'"><xsl:text>Manobo-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='glv'"><xsl:text>Manx</xsl:text></xsl:when>
 <xsl:when test="$code='mao'"><xsl:text>Maori</xsl:text></xsl:when>
 <xsl:when test="$code='arn'"><xsl:text>Mapuche</xsl:text></xsl:when>
 <xsl:when test="$code='mar'"><xsl:text>Marathi</xsl:text></xsl:when>
 <xsl:when test="$code='chm'"><xsl:text>Mari</xsl:text></xsl:when>
 <xsl:when test="$code='mah'"><xsl:text>Marshallesisch</xsl:text></xsl:when>
 <xsl:when test="$code='mwr'"><xsl:text>Marwari</xsl:text></xsl:when>
 <xsl:when test="$code='mas'"><xsl:text>Maasai</xsl:text></xsl:when>
 <xsl:when test="$code='myn'"><xsl:text>Maya-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='men'"><xsl:text>Mende</xsl:text></xsl:when>
 <xsl:when test="$code='mic'"><xsl:text>Míkmawísimk</xsl:text></xsl:when>
 <xsl:when test="$code='min'"><xsl:text>Minangkabauisch</xsl:text></xsl:when>
 <xsl:when test="$code='mwl'"><xsl:text>Mirandés</xsl:text></xsl:when>
 <xsl:when test="$code='mis'"><xsl:text>Verschiedene Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='moh'"><xsl:text>Mohawk</xsl:text></xsl:when>
 <xsl:when test="$code='mdf'"><xsl:text>Moksha</xsl:text></xsl:when>
 <xsl:when test="$code='mkh'"><xsl:text>Mon-Khmer (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='lol'"><xsl:text>Mongo-Nkundu</xsl:text></xsl:when>
 <xsl:when test="$code='mon'"><xsl:text>Mongolisch</xsl:text></xsl:when>
 <xsl:when test="$code='cnr'"><xsl:text>Montenegrinisch</xsl:text></xsl:when>
 <xsl:when test="$code='mos'"><xsl:text>Mooré</xsl:text></xsl:when>
 <xsl:when test="$code='mul'"><xsl:text>Verschiedene Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='mun'"><xsl:text>Munda (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='nah'"><xsl:text>Nahuatl</xsl:text></xsl:when>
 <xsl:when test="$code='nau'"><xsl:text>Nauru</xsl:text></xsl:when>
 <xsl:when test="$code='nav'"><xsl:text>Navajo</xsl:text></xsl:when>
 <xsl:when test="$code='nbl'"><xsl:text>Ndebele (Südafrika)</xsl:text></xsl:when>
 <xsl:when test="$code='nde'"><xsl:text>Ndebele (Simbabwe)</xsl:text></xsl:when>
 <xsl:when test="$code='ndo'"><xsl:text>Ndonga</xsl:text></xsl:when>
 <xsl:when test="$code='nap'"><xsl:text>Neapolitanisch</xsl:text></xsl:when>
 <xsl:when test="$code='nep'"><xsl:text>Nepalesisch</xsl:text></xsl:when>
 <xsl:when test="$code='new'"><xsl:text>Newari</xsl:text></xsl:when>
 <xsl:when test="$code='nwc'"><xsl:text>Alt-Newari</xsl:text></xsl:when>
 <xsl:when test="$code='nia'"><xsl:text>Nias</xsl:text></xsl:when>
 <xsl:when test="$code='nic'"><xsl:text>Niger-Kordofanische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='ssa'"><xsl:text>Nilosaharanische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='niu'"><xsl:text>Niueanisch</xsl:text></xsl:when>
 <xsl:when test="$code='nqo'"><xsl:text>N'ko</xsl:text></xsl:when>
 <xsl:when test="$code='nog'"><xsl:text>Nogaisch</xsl:text></xsl:when>
 <xsl:when test="$code='zxx'"><xsl:text>Kein sprachlicher Inhalt</xsl:text></xsl:when>
 <xsl:when test="$code='nai'"><xsl:text>Nordamerikanische Indianersprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='frr'"><xsl:text>Nordfriesisch</xsl:text></xsl:when>
 <xsl:when test="$code='sme'"><xsl:text>Nordsamisch</xsl:text></xsl:when>
 <xsl:when test="$code='nso'"><xsl:text>Nord-Sotho</xsl:text></xsl:when>
 <xsl:when test="$code='nor'"><xsl:text>Norwegisch</xsl:text></xsl:when>
 <xsl:when test="$code='nob'"><xsl:text>Norwegisch (Bokmål)</xsl:text></xsl:when>
 <xsl:when test="$code='nno'"><xsl:text>Norwegisch (Nynorsk)</xsl:text></xsl:when>
 <xsl:when test="$code='nub'"><xsl:text>Nubische Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='nym'"><xsl:text>Nyamwesi</xsl:text></xsl:when>
 <xsl:when test="$code='nya'"><xsl:text>Nyanja</xsl:text></xsl:when>
 <xsl:when test="$code='nyn'"><xsl:text>Nyankole</xsl:text></xsl:when>
 <xsl:when test="$code='nyo'"><xsl:text>Runyoro</xsl:text></xsl:when>
 <xsl:when test="$code='nzi'"><xsl:text>Nzema</xsl:text></xsl:when>
 <xsl:when test="$code='oci'"><xsl:text>Okzitanisch (nach 1500)</xsl:text></xsl:when>
 <xsl:when test="$code='xal'"><xsl:text>Oiratisch</xsl:text></xsl:when>
 <xsl:when test="$code='oji'"><xsl:text>Ojibwa</xsl:text></xsl:when>
 <xsl:when test="$code='non'"><xsl:text>Altnordisch</xsl:text></xsl:when>
 <xsl:when test="$code='peo'"><xsl:text>Altpersisch (ca. 600-400 v.Chr.)</xsl:text></xsl:when>
 <xsl:when test="$code='ori'"><xsl:text>Oriya</xsl:text></xsl:when>
 <xsl:when test="$code='orm'"><xsl:text>Oromo</xsl:text></xsl:when>
 <xsl:when test="$code='osa'"><xsl:text>Osage</xsl:text></xsl:when>
 <xsl:when test="$code='oss'"><xsl:text>Ossetisch</xsl:text></xsl:when>
 <xsl:when test="$code='oto'"><xsl:text>Oto-Pame-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='pal'"><xsl:text>Pahlavi</xsl:text></xsl:when>
 <xsl:when test="$code='pau'"><xsl:text>Palauisch</xsl:text></xsl:when>
 <xsl:when test="$code='pli'"><xsl:text>Pali</xsl:text></xsl:when>
 <xsl:when test="$code='pam'"><xsl:text>Pampangisch</xsl:text></xsl:when>
 <xsl:when test="$code='pag'"><xsl:text>Pangasinesisch</xsl:text></xsl:when>
 <xsl:when test="$code='pan'"><xsl:text>Panjabi</xsl:text></xsl:when>
 <xsl:when test="$code='pap'"><xsl:text>Papiamentu</xsl:text></xsl:when>
 <xsl:when test="$code='paa'"><xsl:text>Papuasprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='per'"><xsl:text>Persisch</xsl:text></xsl:when>
 <xsl:when test="$code='phi'"><xsl:text>Philippinische Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='phn'"><xsl:text>Phönizisch</xsl:text></xsl:when>
 <xsl:when test="$code='pon'"><xsl:text>Ponapeanisch</xsl:text></xsl:when>
 <xsl:when test="$code='pol'"><xsl:text>Polnisch</xsl:text></xsl:when>
 <xsl:when test="$code='por'"><xsl:text>Portugiesisch</xsl:text></xsl:when>
 <xsl:when test="$code='pra'"><xsl:text>Prakrit</xsl:text></xsl:when>
 <xsl:when test="$code='pro'"><xsl:text>Provenzalisch (bis 1500)</xsl:text></xsl:when>
 <xsl:when test="$code='pus'"><xsl:text>Paschtunisch</xsl:text></xsl:when>
 <xsl:when test="$code='que'"><xsl:text>Quechua</xsl:text></xsl:when>
 <xsl:when test="$code='roh'"><xsl:text>Rätoromanisch</xsl:text></xsl:when>
 <xsl:when test="$code='raj'"><xsl:text>Rajasthani</xsl:text></xsl:when>
 <xsl:when test="$code='rap'"><xsl:text>Rapanui</xsl:text></xsl:when>
 <xsl:when test="$code='rar'"><xsl:text>Rarotonganisch</xsl:text></xsl:when>
 <xsl:when test="$code='roa'"><xsl:text>Romanisch (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='rom'"><xsl:text>Romani</xsl:text></xsl:when>
 <xsl:when test="$code='rum'"><xsl:text>Rumänisch</xsl:text></xsl:when>
 <xsl:when test="$code='run'"><xsl:text>Kirundi</xsl:text></xsl:when>
 <xsl:when test="$code='rus'"><xsl:text>Russisch</xsl:text></xsl:when>
 <xsl:when test="$code='sal'"><xsl:text>Salish-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='sam'"><xsl:text>Samaritanisch</xsl:text></xsl:when>
 <xsl:when test="$code='smi'"><xsl:text>Samisch</xsl:text></xsl:when>
 <xsl:when test="$code='smo'"><xsl:text>Samoanisch</xsl:text></xsl:when>
 <xsl:when test="$code='sad'"><xsl:text>Sandawe</xsl:text></xsl:when>
 <xsl:when test="$code='sag'"><xsl:text>Sango (Ubangi-Kreol)</xsl:text></xsl:when>
 <xsl:when test="$code='san'"><xsl:text>Sanskrit</xsl:text></xsl:when>
 <xsl:when test="$code='sat'"><xsl:text>Santali</xsl:text></xsl:when>
 <xsl:when test="$code='srd'"><xsl:text>Sardisch</xsl:text></xsl:when>
 <xsl:when test="$code='sas'"><xsl:text>Sasak</xsl:text></xsl:when>
 <xsl:when test="$code='sco'"><xsl:text>Scots</xsl:text></xsl:when>
 <xsl:when test="$code='gla'"><xsl:text>Schottisch-gälisch</xsl:text></xsl:when>
 <xsl:when test="$code='sel'"><xsl:text>Selkupisch</xsl:text></xsl:when>
 <xsl:when test="$code='sem'"><xsl:text>Semitisch (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='srp'"><xsl:text>Serbisch</xsl:text></xsl:when>
 <xsl:when test="$code='srr'"><xsl:text>Serer</xsl:text></xsl:when>
 <xsl:when test="$code='shn'"><xsl:text>Shan</xsl:text></xsl:when>
 <xsl:when test="$code='sna'"><xsl:text>Shona</xsl:text></xsl:when>
 <xsl:when test="$code='iii'"><xsl:text>Yi</xsl:text></xsl:when>
 <xsl:when test="$code='scn'"><xsl:text>Sizilianisch</xsl:text></xsl:when>
 <xsl:when test="$code='sid'"><xsl:text>Sidama</xsl:text></xsl:when>
 <xsl:when test="$code='sgn'"><xsl:text>Gebärdensprachen</xsl:text></xsl:when>
 <xsl:when test="$code='bla'"><xsl:text>Siksika</xsl:text></xsl:when>
 <xsl:when test="$code='snd'"><xsl:text>Sindhi</xsl:text></xsl:when>
 <xsl:when test="$code='sin'"><xsl:text>Singhalesisch</xsl:text></xsl:when>
 <xsl:when test="$code='sit'"><xsl:text>Sinotibetisch (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='sio'"><xsl:text>Sioux-Sprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='sms'"><xsl:text>Skoltsamisch</xsl:text></xsl:when>
 <xsl:when test="$code='den'"><xsl:text>Slavey</xsl:text></xsl:when>
 <xsl:when test="$code='sla'"><xsl:text>Slawisch (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='slo'"><xsl:text>Slowakisch</xsl:text></xsl:when>
 <xsl:when test="$code='slv'"><xsl:text>Slowenisch</xsl:text></xsl:when>
 <xsl:when test="$code='sog'"><xsl:text>Sogdisch</xsl:text></xsl:when>
 <xsl:when test="$code='som'"><xsl:text>Somalisch</xsl:text></xsl:when>
 <xsl:when test="$code='son'"><xsl:text>Songhai</xsl:text></xsl:when>
 <xsl:when test="$code='snk'"><xsl:text>Soninke</xsl:text></xsl:when>
 <xsl:when test="$code='wen'"><xsl:text>Sorbisch (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='sot'"><xsl:text>Sotho</xsl:text></xsl:when>
 <xsl:when test="$code='sai'"><xsl:text>Südamerikanische Indianersprachen (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='sma'"><xsl:text>Südsamisch</xsl:text></xsl:when>
 <xsl:when test="$code='spa'"><xsl:text>Spanisch</xsl:text></xsl:when>
 <xsl:when test="$code='srn'"><xsl:text>Sranan</xsl:text></xsl:when>
 <xsl:when test="$code='suk'"><xsl:text>Sukuma</xsl:text></xsl:when>
 <xsl:when test="$code='sux'"><xsl:text>Sumerisch</xsl:text></xsl:when>
 <xsl:when test="$code='sun'"><xsl:text>Sundanesisch</xsl:text></xsl:when>
 <xsl:when test="$code='sus'"><xsl:text>Susu</xsl:text></xsl:when>
 <xsl:when test="$code='swa'"><xsl:text>Swahili</xsl:text></xsl:when>
 <xsl:when test="$code='ssw'"><xsl:text>Siswati</xsl:text></xsl:when>
 <xsl:when test="$code='swe'"><xsl:text>Schwedisch</xsl:text></xsl:when>
 <xsl:when test="$code='gsw'"><xsl:text>Schweizerdeutsch</xsl:text></xsl:when>
 <xsl:when test="$code='syc'"><xsl:text>Syrisch</xsl:text></xsl:when>
 <xsl:when test="$code='syr'"><xsl:text>Modernes syrisch</xsl:text></xsl:when>
 <xsl:when test="$code='tgl'"><xsl:text>Tagalog</xsl:text></xsl:when>
 <xsl:when test="$code='tah'"><xsl:text>Tahitianisch</xsl:text></xsl:when>
 <xsl:when test="$code='tai'"><xsl:text>Tai (Weitere)</xsl:text></xsl:when>
 <xsl:when test="$code='tgk'"><xsl:text>Tajik</xsl:text></xsl:when>
 <xsl:when test="$code='tmh'"><xsl:text>Tuareg</xsl:text></xsl:when>
 <xsl:when test="$code='tam'"><xsl:text>Tamilisch</xsl:text></xsl:when>
 <xsl:when test="$code='tat'"><xsl:text>Tatarisch</xsl:text></xsl:when>
 <xsl:when test="$code='tel'"><xsl:text>Telugu</xsl:text></xsl:when>
 <xsl:when test="$code='tem'"><xsl:text>Temne</xsl:text></xsl:when>
 <xsl:when test="$code='ter'"><xsl:text>Terena</xsl:text></xsl:when>
 <xsl:when test="$code='tet'"><xsl:text>Tetum</xsl:text></xsl:when>
 <xsl:when test="$code='tha'"><xsl:text>Thai</xsl:text></xsl:when>
 <xsl:when test="$code='tib'"><xsl:text>Tibetisch</xsl:text></xsl:when>
 <xsl:when test="$code='tig'"><xsl:text>Tigré</xsl:text></xsl:when>
 <xsl:when test="$code='tir'"><xsl:text>Tigrinya</xsl:text></xsl:when>
 <xsl:when test="$code='tiv'"><xsl:text>Tiv</xsl:text></xsl:when>
 <xsl:when test="$code='tli'"><xsl:text>Tlingit</xsl:text></xsl:when>
 <xsl:when test="$code='tpi'"><xsl:text>Tok Pisin</xsl:text></xsl:when>
 <xsl:when test="$code='tkl'"><xsl:text>Tokelauisch</xsl:text></xsl:when>
 <xsl:when test="$code='tog'"><xsl:text>Tonga (Nyasa)</xsl:text></xsl:when>
 <xsl:when test="$code='ton'"><xsl:text>Tongaisch</xsl:text></xsl:when>
 <xsl:when test="$code='tsi'"><xsl:text>Tsimshian</xsl:text></xsl:when>
 <xsl:when test="$code='tso'"><xsl:text>Xitsonga</xsl:text></xsl:when>
 <xsl:when test="$code='tsn'"><xsl:text>Setswana</xsl:text></xsl:when>
 <xsl:when test="$code='tum'"><xsl:text>Tumbuka</xsl:text></xsl:when>
 <xsl:when test="$code='tup'"><xsl:text>Tupí-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='tur'"><xsl:text>Türkisch</xsl:text></xsl:when>
 <xsl:when test="$code='ota'"><xsl:text>Osmanisches türkisch</xsl:text></xsl:when>
 <xsl:when test="$code='tuk'"><xsl:text>Turkmenisch</xsl:text></xsl:when>
 <xsl:when test="$code='tvl'"><xsl:text>Tuvaluisch</xsl:text></xsl:when>
 <xsl:when test="$code='tyv'"><xsl:text>Tuwinisch</xsl:text></xsl:when>
 <xsl:when test="$code='twi'"><xsl:text>Twi</xsl:text></xsl:when>
 <xsl:when test="$code='udm'"><xsl:text>Udmurtisch</xsl:text></xsl:when>
 <xsl:when test="$code='uga'"><xsl:text>Ugaritisch</xsl:text></xsl:when>
 <xsl:when test="$code='uig'"><xsl:text>Uigurisch</xsl:text></xsl:when>
 <xsl:when test="$code='ukr'"><xsl:text>Ukrainisch</xsl:text></xsl:when>
 <xsl:when test="$code='umb'"><xsl:text>Umbundu</xsl:text></xsl:when>
 <xsl:when test="$code='und'"><xsl:text>Nicht definiert</xsl:text></xsl:when>
 <xsl:when test="$code='hsb'"><xsl:text>Obersorbisch</xsl:text></xsl:when>
 <xsl:when test="$code='urd'"><xsl:text>Urdu</xsl:text></xsl:when>
 <xsl:when test="$code='uzb'"><xsl:text>Usbekisch</xsl:text></xsl:when>
 <xsl:when test="$code='vai'"><xsl:text>Vai</xsl:text></xsl:when>
 <xsl:when test="$code='ven'"><xsl:text>Tshivenda</xsl:text></xsl:when>
 <xsl:when test="$code='vie'"><xsl:text>Vietnamesisch</xsl:text></xsl:when>
 <xsl:when test="$code='vol'"><xsl:text>Volapük</xsl:text></xsl:when>
 <xsl:when test="$code='vot'"><xsl:text>Wotisch</xsl:text></xsl:when>
 <xsl:when test="$code='wak'"><xsl:text>Wakash-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='wln'"><xsl:text>Wallonisch</xsl:text></xsl:when>
 <xsl:when test="$code='war'"><xsl:text>Wáray-Wáray</xsl:text></xsl:when>
 <xsl:when test="$code='was'"><xsl:text>Washoe</xsl:text></xsl:when>
 <xsl:when test="$code='wel'"><xsl:text>Walisisch</xsl:text></xsl:when>
 <xsl:when test="$code='him'"><xsl:text>West-Pahari-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='wal'"><xsl:text>Wolaytta</xsl:text></xsl:when>
 <xsl:when test="$code='wol'"><xsl:text>Wolof</xsl:text></xsl:when>
 <xsl:when test="$code='xho'"><xsl:text>Xhosa</xsl:text></xsl:when>
 <xsl:when test="$code='sah'"><xsl:text>Jakutisch</xsl:text></xsl:when>
 <xsl:when test="$code='yao'"><xsl:text>Yao (Afrika)</xsl:text></xsl:when>
 <xsl:when test="$code='yap'"><xsl:text>Yapesisch</xsl:text></xsl:when>
 <xsl:when test="$code='yid'"><xsl:text>Jiddisch</xsl:text></xsl:when>
 <xsl:when test="$code='yor'"><xsl:text>Yoruba</xsl:text></xsl:when>
 <xsl:when test="$code='ypk'"><xsl:text>Yupik-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='znd'"><xsl:text>Zande-Sprachen</xsl:text></xsl:when>
 <xsl:when test="$code='zap'"><xsl:text>Zapotekisch</xsl:text></xsl:when>
 <xsl:when test="$code='zza'"><xsl:text>Zazaisch</xsl:text></xsl:when>
 <xsl:when test="$code='zen'"><xsl:text>Zenaga</xsl:text></xsl:when>
 <xsl:when test="$code='zha'"><xsl:text>Zhuang</xsl:text></xsl:when>
 <xsl:when test="$code='zul'"><xsl:text>Zulu</xsl:text></xsl:when>
 <xsl:when test="$code='zun'"><xsl:text>Zuñi</xsl:text></xsl:when>
 <xsl:otherwise>
 <!-- when 041$a is mapped to an authorised value list, this will show the description -->
 <xsl:value-of select="$code" />
 </xsl:otherwise>
 </xsl:choose>
 </xsl:template>
</xsl:stylesheet>
